### ISSUE TITLE
Enemies textures issue

### ISSUE THREAD

**Issue by jamesrmuir** [ducsuus/Game_001#47]
They have the dead image when they spawn and will not reverse

**Comment by ducsuus** [comment]
Ack - this was fixed in one of the recent master commits, merge the master into your branch.

**Comment by ducsuus** [comment]
Ack - this was fixed in one of the recent master commits, merge the master into your branch.

**Comment by ducsuus** [comment]
Ack - this was fixed in one of the recent master commits, merge the master into your branch.

**Comment by jamesrmuir** [comment]
I just have but the image is still not flipping so they keep running backwords

**Comment by ducsuus** [comment]
Hmm - I'll have a look when I'm at the cohub :)
